pydjangoenv/grubfood/grubfood/urls.py
from django.contrib import admin
from django.urls import include, path
# from django.http import HttpResponse

def index(request):
    return HttpResponse('<p>Hello! Welcome to <b>GrubFood</b>!<p>')

def fgrub(request):
    return HttpResponse('<p>Our featured grub for today is <b>Salmon Sashimi</b>!</p>')

urlpatterns = [
    # path('', index),
    # path('featuredgrub/', fgrub),
    path('webkiosk/', include('webkiosk.urls')),
    path('admin/', admin.site.urls),
]

# user can visit a url - 127.0.0.1:8000/featuredgrub
# our web app will return to the user:
# our featured grub for today is Salmon Sashimi! (Salmon Sashimi will be in bold)

pydjangoenv/grubfood/webkiosk/urls.py
from django.urls import path
from . import views  # from . means look into the same folder of this current file

app_name = 'webkiosk'
urlpatterns = [
    path('', views.index, name='index'),  # 127.0.0.1:8000/webkiosk
    path('food/', views.listfood, name='food-list'),
    path('food/new/', views.createfood, name='food-create'),
    path('food/<int:pk>/', views.detailfood, name='food-detail'),
    path('food/<int:pk>/edit/', views.updatefood, name='food-update'),
    path('food/<int:pk>/delete/', views.deletefood, name='food-delete')
    # path('testview/', views.tv), # 127.0.0.1:8000/webkiosk/testview
]

# webkiosk/food/1

pydjangoenv/grubfood/webkiosk/models.py
from django.db import models

# Create your models here.
# the tables


class Customer(models.Model):
    firstname = models.CharField(max_length=20)
    lastname = models.CharField(max_length=20)
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.id}: {self.firstname} {self.lastname}, {self.address}, {self.city}'


class Food(models.Model):
    name = models.CharField(max_length=20)
    description = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return f'{self.id}: {self.name}, {self.description}, {self.price}'

# the orders table must have a Foreign Key because it will be connected to the Customer and Food tables


class Order(models.Model):
    PAYMENT_MODE_CHOICES = [
        ('CH', 'Cash'),
        ('CD', 'Card')
    ]
    orderdatetime = models.DateTimeField(auto_now_add=True)
    paymentmode = models.CharField(max_length=2, choices=PAYMENT_MODE_CHOICES)
    quantity = models.IntegerField()

    food = models.ForeignKey(Food, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.id}: {self.customer.firstname} {self.customer.lastname}, {self.food.name}, {self.quantity}, {self.paymentmode}, {self.orderdatetime}'

pydjangoenv/grubfood/webkiosk/forms.py
from django.forms import ModelForm
from .models import Customer, Food, Order

class FoodForm(ModelForm):
    class Meta:
        model = Food
        fields = ['name', 'description', 'price']
        

pydjangoenv/grubfood/webkiosk/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages

from .models import Customer, Food, Order
from .forms import FoodForm

# Create your views here.


def index(request):
    # return HttpResponse('<p>Welcome to the GrubFood Web Kiosk!</p>')
    return render(request, 'webkiosk/welcome.html')


def listfood(request):
    context = {
        'foodlist': Food.objects.all(),
        'testitem': 'chair'
    }
    return render(request, 'webkiosk/food.html', context)


def createfood(request):
    if request.method == 'GET':  # just getting the data -- like when you're just visiting the form page
        form = FoodForm()  # you create an empty food form
    elif request.method == 'POST':  # when you click submit in the form, it makes a POST request
        # insert new food record, it will contain the data that will be typed into the form
        form = FoodForm(request.POST)
        if form.is_valid():  # if the form is valid
            form.save()  # we save the form; adds a record to the database
            return redirect('webkiosk:food-list')

    context = {'form': form}
    return render(request, 'webkiosk/food_form.html', context)


def detailfood(request, pk):  # pk is a primary key which is a parameter in urls
    food = Food.objects.get(id=pk)

    context = {'food': food}
    return render(request, 'webkiosk/food_detail.html', context)


def updatefood(request, pk):
    food = Food.objects.get(id=pk)
    if request.method == 'GET':
        form = FoodForm(instance=food)
    elif request.method == 'POST':
        # instance is to specify which food record we want to update
        form = FoodForm(request.POST, instance=food)
        if form.is_valid():
            form.save()
            messages.success(request, 'Food record successfully updated.')

    context = {'form': form}
    return render(request, 'webkiosk/food_form.html', context)


def deletefood(request, pk):
    food = Food.objects.get(id=pk)
    if request.method == 'GET':
        context = {'food': food}
        return render(request, 'webkiosk/food_delete.html', context)
    elif request.method == 'POST':
        food.delete()
        return redirect('webkiosk:food-list')

pydjangoenv/grubfood/webkiosk/templates/webkiosk/base.html
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>{% block pagetitle %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'webkiosk/styles/main.css' %}">
    </head>
    <body>
        <header>
            <h1>GrubFood</h1>
            <p>Grub your food now!</p>
            <img src="{% static 'webkiosk/images/cat.png' %}">
        </header>

        {% block mainnav %}
        <nav>
            <ul>
                <li><a href="{% url 'webkiosk:food-list' %}">Food Menu</a></li>
                <li><a href="{% url 'webkiosk:food-create' %}">Add Food</a></li>
            </ul>
        </nav>
        {% endblock %}

        <main>
            {% block maincontent %}

            {% endblock %}
        </main>
    </body>
</html>

pydjangoenv/grubfood/webkiosk/templates/webkiosk/food.html
{% extends 'webkiosk/base.html' %}

{% block pagetitle %}Grubfood - Food List{% endblock %}

{% block maincontent %}
<h2>Menu</h2>
<ol> 
    {% for food in foodlist %}
        <li>{{ food.name }} | Php {{ food.price }} |
            <a href="{% url 'webkiosk:food-detail' food.id %}">More Info</a> |
            <a href="{% url 'webkiosk:food-update' food.id %}">Edit</a> |
            <a href="{% url 'webkiosk:food-delete' food.id %}">Delete</a>
            </li>
    {% endfor %}
</ol>
<p>The value of testiem is {{ testitem }}.</p>
{% endblock %}

pydjangoenv/grubfood/webkiosk/templates/webkiosk/food_delete.html
{% extends 'webkiosk/base.html' %}

{% block pagetitle %}GrubFood - Delete {{ food.name }}{% endblock %}

{% block mainnav %}{% endblock %}

{% block maincontent %}
<h2>Delete Food</h2>
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete <b>{{ food.name }}?</b></p>
    <a href="{% url 'webkiosk:food-list' %}">Cancel</a>
    <input type="submit" value="Yes">
</form>
{% endblock %}

pydjangoenv/grubfood/webkiosk/templates/webkiosk/food_detail.html
{% extends 'webkiosk/base.html' %}

{% block pagetitle %}Grubfood - {{food.name }}{% endblock %}

{% block maincontent %}
<h2>{{ food.name }}</h2>
<ul>
    <li>Description: {{ food.description }}</li>
    <li>Description: {{ food.price }}</li>
</ul>
{% endblock %}

localhost:8000/webkiosk/food/1

pydjangoenv/grubfood/webkiosk/templates/webkiosk/food_form.html
{% extends 'webkiosk/base.html' %}

{% block pagetitle %}Grubfood - Add or Edit Form{% endblock %}

{% block maincontent %}
<h2>Add or Edit Food</h2>

<form method="post">
    {% csrf_token %} <!-- cross site request forgery -->
    {{ form.as_ul }} <!-- template variable named form -->
    <input type="submit" value="Submit">
</form>

<ul>
    {% for message in messages %}
        <li>{{ message }}</li>
    {% endfor %}
</ul>

{% endblock %}

pydjangoenv/grubfood/webkiosk/templates/webkiosk/welcome.html
{% extends 'webkiosk/base.html' %}

{% block pagetitle %}GrubFood Web Kiosk :){% endblock %}

{% block maincontent %}
<h2>Welcome!</h2>
<p>Welcome to the GrubFood Web Kiosk! Have a nice day! :)</p>
{% endblock %}